var num1=40
var num2=0;
try{
    if(num2==0) throw exception
    var result=num1/num2;
   console.log(result);
}
catch(error){
    console.log("exception");
    
}
